### ISSUE TITLE
package.json no tiene dependencies

### ISSUE THREAD

**Issue by a0viedo** [AquiGorka/remote-device#1]
Es por alguna razón en particular? Veo que usás al menos Express y socket.io, podrías hacer `npm install socket.io express --save` y las agregaría automáticamente.

**Comment by AquiGorka** [comment]
Si, si, estuve jugando con eso, aun no actualizo. Lo pudiste probar.

Saludos,
Gorka

**Comment by a0viedo** [comment]
Qué onda gorka? ya estás para dar esta charla?

**Comment by AquiGorka** [comment]
Con mucho gusto! Cuando?

Saludos,
Gorka
